repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: (deployment|template)\.yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
-   repo: https://github.com/pyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: ["--remove-all-unused-imports", "--remove-duplicate-keys", "--remove-unused-variables"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-PyYAML]
        exclude: (tests)/.*
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [--fix]
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
