name: Lint and Test

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python - --version 1.8.4
    - name: Install dependencies
      run: |
        poetry install
    - name: Analysing the code with pylint
      run: |
        poetry run pylint src
    - name: Running tests
      run: |
        poetry run pytest tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGDATABASE: postgres
        PGPASSWORD: postgres
